all:
  children:
    srlinux:
      hosts:
        spine1:
          ansible_host: 172.80.80.21
        spine2:
          ansible_host: 172.80.80.22
    nxos:
      hosts:
        leaf2:
          ansible_host: 172.80.80.12
    junos:
      hosts:
        leaf1:
          ansible_host: 172.80.80.11
        leaf3:
          ansible_host: 172.80.80.13
