---
- name: Ansible Test
  hosts: all
  tasks:
    - name: underlay interface
      block:
        - name: configure underlays interface
          when: "'junos' in group_names"
          ansible.netcommon.cli_config:
            config: "{{ lookup('template', 'templates/junos/1_underlay_interfaces.j2') }}"
