{
 "title": "Thesis EVPN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Services",
    "query": {
     "query": "label_values(network_instance_name)"
    }
   },
   {
    "name": "Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "DC State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DC Fabric Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "interface_traffic_rate_in_bps", "legendFormat": "__auto" },
    { "expr": "interface_traffic_rate_out_bps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Telemetry",
   "type": "andrewbmchugh-flow-panel",
   "gridPos": { "h": 16, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "interface_oper_state",
     "legendFormat": "oper-state:{{source}}:{{interface_name}}"
    },
    {
     "expr": "interface_traffic_rate_out_bps",
     "legendFormat": "{{source}}:{{interface_name}}:out"
    },
    {
     "expr": "interface_traffic_rate_in_bps",
     "legendFormat": "{{source}}:{{interface_name}}:in"
    }
   ]
  },
  {
   "title": "Service: $Services",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "network_instance_oper_state{network_instance_name='$Services'}",
     "legendFormat": "{{source}}"
    }
   ]
  },
  { "title": "$NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Routing Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_total_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Total Routes"
    },
    {
     "expr": "network_instance_route_table_ipv4_unicast_statistics_active_routes_with_ecmp{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "IPv4 Active ECMP Routes"
    }
   ]
  },
  {
   "title": "BGP Peer stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_up_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Up Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Peers"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_disabled_peers{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Disabled Peers"
    }
   ]
  },
  {
   "title": "BGP Route Stats",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_instance_protocols_bgp_statistics_total_received_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Received Routes"
    },
    {
     "expr": "network_instance_protocols_bgp_statistics_total_active_routes{network_instance_name=\"default\",source=\"$NE\"}",
     "legendFormat": "Total Active Routes"
    }
   ]
  },
  { "title": "Logging $NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Log: $Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{application=\"$Logs\", source=\"$NE\"}"
    }
   ]
  }
 ]
}