interfaces:
    ethernet-1/1:
        address: '192.168.12.1/31'
        mtu: 9000
    ethernet-1/2:
        address: '192.168.22.1/31'
        mtu: 9000
    ethernet-1/3:
        address: '192.168.32.1/31'
        mtu: 9000
    system0:
        address: '10.0.2.2/32'
bgp:
    ebgp_as: 202
    ibgp_as: 100
    router_id: '10.0.2.2'
    cluster_id: '20.20.20.20'
    neighbors:
        192.168.12.0:
                remote_as: 101
        192.168.22.0:
                remote_as: 102
        192.168.32.0:
                remote_as: 103
remote_server:
    address: '172.80.80.45'
    port: 1514