---
ansible_connection: ansible.netcommon.network_cli
#ansible_connection: ansible.netcommon.httpapi
ansible_network_os: cisco.nxos.nxos
ansible_user: admin
ansible_password: admin
ansible_become: true
ansible_become_method: enable
